### ISSUE TITLE
Running on bitbucket pipeplines

### ISSUE THREAD

**Issue by antarr** [shakacode/cypress-on-rails#125]
I'm trying to configure Cypress to run on using BitBucket pipelines. It's hanging when the server starts and the test never run until the build times out.

**bitbucket-pipelines.yml**
```yml
image: ruby:2.7.8-slim-bullseye

pipelines:
  default:
    - step:
        name: Test
        caches:
          - bundler
          - yarn
          - mysql
        script:
          - apt-get update && apt-get install -y build-essential libmariadb-dev libmagickwand-dev shared-mime-info ruby-mimemagic libmariadb-dev-compat nodejs yarn
          - gem install bundler:2.3.26    
          - bundle install --jobs 4 --retry 3 --path vendor/bundle
          - export DATABASE_URL=mysql2://root:root@127.0.0.1:3306/pipelines
          - RAILS_ENV=test bundle exec rails db:schema:load db:migrate
          - bundle exec rspec spec
          # - cd spec && yarn install && cd ..
          - CYPRESS=1 bundle exec rails s -p 5017 &&  cd spec && yarn run cypress run
        services:
          - mysql
definitions:
  services:
    mysql:
      image: mysql:8.0.26
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: pipelines
  caches:
    bundler: vendor/bundle
    yarn: node_modules
    mysql: /var/lib/mysql
```
