### ISSUE TITLE
cypress-on-rails on Github Actions 

### ISSUE THREAD

**Issue by stoplion** [shakacode/cypress-on-rails#61]
Hello..

Are there any guides for getting `cypress-on-rails` to run on `Github Actions`?

Merging together actions from RoR and the [official Cypress Action](https://github.com/cypress-io/github-action)

```
name: End to end tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:10
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install deps
        run: sudo apt-get install libpq-dev

      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create RAILS_ENV=test
          bundle exec rake db:schema:load RAILS_ENV=test
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v1
        with:
          start: bundle exec rails s -e test
          wait-on: http://localhost:3000
          spec: spec/cypress/integration
```

Things bomb out at the `Run Cypress Tests` step..

```
Can't run because no spec files were found.

We searched for any files matching this glob pattern:

spec/cypress/integration
Error: The process '/usr/local/bin/npx' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1188:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1171:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1071:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
##[error]The process '/usr/local/bin/npx' failed with exit code 1
```

**Comment by grantspeelman** [comment]
unfortunately we don't have any guides :(
Sorry

**Comment by jondkinney** [comment]
@stoplion your snippet actually got me a good bit further than I had found anywhere else. Here's what ultimately ended up working for me: 

```
name: End to end tests

on: [push]

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - uses: actions/cache@v2
        with:
          path: 'vendor/bundle'
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install
        env:
          FONT_AWESOME_AUTH_TOKEN: ${{ secrets.FONT_AWESOME_AUTH_TOKEN }}

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          project: ./spec
          start: bundle exec rails s -e test -p 5017
          wait-on: http://localhost:5017
        env:
          FONT_AWESOME_AUTH_TOKEN: ${{ secrets.FONT_AWESOME_AUTH_TOKEN }}
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
```
